# Generated by Django 2.2 on 2019-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190414_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
