# Generated by Django 2.2 on 2019-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190414_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/'),
        ),
    ]
